### ISSUE TITLE
Extending jquery with plugins

### ISSUE THREAD

**Issue by Lupus** [gopherjs/jquery#12]
I'm trying to wrap jQuery with local structure that adds support for Parsley plugin like this:

```go
import (
        "github.com/gopherjs/gopherjs/js"
        "github.com/gopherjs/jquery"
)

type Parsley struct {
        *js.Object
}

type JQuery struct {
        *jquery.JQuery
}

func (j *JQuery) Parsley(options interface{}) *Parsley {
        return &Parsley{j.Underlying().Call("parsley", options)}
}

func jQuery(args ...interface{}) JQuery {
        orig_jquery := jquery.NewJQuery(args)
        return JQuery{&orig_jquery}
}
```

The following code triggers the exception:

```go
jQuery("#some-element-id").FadeOut(500)
```

The exception itself:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'opacity' in undefined
Fa @ jquery-2.1.4.min.js:3
n.extend.css @ jquery-2.1.4.min.js:3
Ka.propHooks._default.get @ jquery-2.1.4.min.js:3
Ka.cur @ jquery-2.1.4.min.js:3
Ka.init @ jquery-2.1.4.min.js:3
Ka @ jquery-2.1.4.min.js:3
h.promise.createTween @ jquery-2.1.4.min.js:3
Ra.* @ jquery-2.1.4.min.js:3
Ua @ jquery-2.1.4.min.js:3
Va @ jquery-2.1.4.min.js:3
Xa @ jquery-2.1.4.min.js:3
n.fn.extend.animate.g @ jquery-2.1.4.min.js:3
n.extend.dequeue @ jquery-2.1.4.min.js:3
(anonymous function) @ jquery-2.1.4.min.js:3
n.extend.each @ jquery-2.1.4.min.js:2
n.fn.n.each @ jquery-2.1.4.min.js:2
n.fn.extend.queue @ jquery-2.1.4.min.js:3
n.fn.extend.animate @ jquery-2.1.4.min.js:3
n.each.n.fn.(anonymous function) @ jquery-2.1.4.min.js:3
$packages.github.com/gopherjs/jquery.B.ptr.FadeOut @ jquery.go:719
$packages.example.com/mywebapp/views.N @ common.go:15
$packages.main.E @ main.go:26
$packages.main.$init @ app.js:106
fun @ app.js:4
$goroutine @ app.js:4
$runScheduled @ app.js:4
```

If I print the result of calling jQuery(...) with `%#v` it prints the following:

```
views.JQuery{JQuery:(*jquery.JQuery)(0x1)}
```

What's the correct way of extending jquery bindings with plugins? In JS it looks like this:

```javascript
$('#my-id').parsley({...})
```

And I wanted to mimic this approach for Go.

**Comment by rusco** [comment]
That should work: I would embed the JQuery Object in the Parsley struct, then make the call "Call("parsley", options)}" from the Parsley Instance. 
I have no concrete example at hand , but I can arrange one if you want.

**Comment by Lupus** [comment]
Here is the working code that I've came up with so far:

```go
type Parsley struct {
        *js.Object
}

func (p *Parsley) Reset() {
        p.Call("reset")
}

func jqParsley(el jquery.JQuery, options interface{}) *Parsley {
        return &Parsley{el.Underlying().Call("parsley")}
}

// Usage example
func main() {
        parsley := jqParsley(jQuery.Find("form"), nil)
}
```

`jqParsley` function looks cumbersome. In JavaScript world jQuery plugins hook their methods into jQuery object itself and I tried to do that in Go via wrapping of jQuery object to include the methods for plugins of interest (Parsley, Bootstrap, JSON-RPC etc).

So I want to have something similar to `$('form').parsley()`, e.g. `jQuery('form').Parsley()`. To achieve that we need to add a method to jQuery object, and Go does not allow this for non-local objects. We could hijack additional file with the plugin wrappers we use along with jquery package, but I would like to avoid this if possible.

**Comment by rusco** [comment]
for example if you use the sample "greenify" plugin defined in JS code:

```js
	(function ($) {
		$.fn.greenify = function( options ) {
			var settings = $.extend({
				color: "#556b2f",
				backgroundColor: "white"
			}, options );
			return this.css({
				color: settings.color,
				backgroundColor: settings.backgroundColor
			});
		};
	}( jQuery ));
```


The easiest way to call this with GopherJS would probably be the "Call" method:

```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
	"github.com/gopherjs/jquery"
)
var jQuery = jquery.NewJQuery 

func main() {
	jQuery("div").Call("greenify", js.M{"color": "orange"})
}
```

**Comment by Lupus** [comment]
Just using ".Call()" seems easy end elegant enough for me.

Thanks for taking your time on this!
