### ISSUE TITLE
row.add(data) method in DataTable plug-in

### ISSUE THREAD

**Issue by SkyGraff** [gopherjs/jquery#21]
Hi guys,

I'm working with the DataTable plug-in and I have a problem with the row.add(data) method.

I initialize my table with:
```go
var jQuery = jquery.NewQuery
table := jQuery("#tablename").Underlying().Call("DataTable", js.M{/*Some parameters*/})
```
then I use this table like this:
```go
tmp := [5]string{"1", "2", "3", "4", "5"}
table.Call("row.add", tmp).Call("draw")
```
but it doesn't work. No compilation error but when executing this part of code I get this error:
`TypeError: c[0][$externalize(...)] is not a function`

If someone know what I do wrong :smiley:

**Comment by kelwang** [comment]
table.Get(“row”).Call(“add”, tmp)

**Comment by SkyGraff** [comment]
It works,

Thanks a lot @kelwang  !
